Repository lonewol7f/EnLearn, pull requests merged in 2021-09, with the labels that each got.

#32 Add Free Quiz Button into Teacher profile page, must rename the page name
  .idea/artifacts/EnLearn_war.xml
  .idea/artifacts/EnLearn_war_exploded.xml
  EnLearn.iml
  src/main/webapp/WEB-INF/view/profile-page-teacher.jsp
Labels: enhancement

#34 swee76-quiz-management-system
  src/main/java/net/enLearn/controller/CourseController.java
  src/main/java/net/enLearn/controller/TeacherController.java
  src/main/webapp/WEB-INF/view/add-free-quiz.jsp
  src/main/webapp/WEB-INF/view/add-special-quiz.jsp
  src/main/webapp/WEB-INF/view/add-video.jsp
  src/main/webapp/WEB-INF/view/header.jsp
  src/main/webapp/WEB-INF/view/profile-page-teacher.jsp
  src/main/webapp/WEB-INF/view/quiz-ans-sub-link.jsp
  src/main/webapp/WEB-INF/view/quiz-select-page.jsp
  src/main/webapp/resources/img/reshot-illustration-teacher-std-free-quiz-pic.png
Labels: enhancement

#35 Lonewol7f comment system
  .gitignore
  .idea/runConfigurations.xml
  .idea/webContexts.xml
  EnLearn.iml
  src/main/java/net/enLearn/dao/CommentDAOImpl.java
  src/main/java/net/enLearn/entity/User.java
  src/main/webapp/resources/js/commentHandler.js
Labels: enhancement, review needed

#36 Create Changes in forms
  .idea/jpa-buddy.xml
  .idea/webContexts.xml
  src/main/java/net/enLearn/controller/TeacherController.java
  src/main/webapp/WEB-INF/view/add-free-quiz.jsp
  src/main/webapp/WEB-INF/view/add-special-quiz.jsp
  src/main/webapp/WEB-INF/view/free-quiz-links.jsp
  src/main/webapp/WEB-INF/view/header.jsp
  src/main/webapp/WEB-INF/view/profile-page-teacher.jsp
  src/main/webapp/resources/css/style.css
Labels: review needed

#41 Lonewol7f comment system
  .idea/artifacts/EnLearn_war.xml
  .idea/artifacts/EnLearn_war_exploded.xml
  .idea/dataSources.xml
  .idea/runConfigurations.xml
  EnLearn.iml
  src/main/java/net/enLearn/controller/CommentController.java
  src/main/java/net/enLearn/dao/NotificationDAO.java
  src/main/java/net/enLearn/dao/NotificationDAOImpl.java
  src/main/java/net/enLearn/service/NotificationService.java
  src/main/java/net/enLearn/service/NotificationServiceImpl.java
  src/main/webapp/resources/js/commentHandler.js
Labels: review needed

#44 Lonewol7f comment system
  .idea/artifacts/EnLearn_war.xml
  .idea/artifacts/EnLearn_war_exploded.xml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/runConfigurations.xml
  EnLearn.iml
  sql_scripts/enlearn.sql
  src/main/java/net/enLearn/controller/AdminController.java
  src/main/java/net/enLearn/controller/DemoController.java
  src/main/java/net/enLearn/dao/AdminDAO.java
  src/main/java/net/enLearn/dao/AdminDAOImpl.java
  src/main/java/net/enLearn/dao/EventDAO.java
  src/main/java/net/enLearn/dao/EventDAOImpl.java
  src/main/java/net/enLearn/entity/Event.java
  src/main/java/net/enLearn/service/AdminService.java
  src/main/java/net/enLearn/service/AdminServiceImpl.java
  src/main/java/net/enLearn/service/EventService.java
  src/main/java/net/enLearn/service/EventServiceImpl.java
  src/main/webapp/WEB-INF/view/admin-panel.jsp
  src/main/webapp/WEB-INF/view/event-form.jsp
  src/main/webapp/WEB-INF/view/event-list.jsp
  src/main/webapp/WEB-INF/view/header.jsp
  src/main/webapp/WEB-INF/view/notification-view.jsp
Labels: review needed

#45 swee76-quiz-management-system
  src/main/java/net/enLearn/controller/CourseController.java
  src/main/java/net/enLearn/controller/TeacherController.java
  src/main/webapp/WEB-INF/view/admin-panel.jsp
  src/main/webapp/WEB-INF/view/marks-and-access.jsp
  src/main/webapp/WEB-INF/view/profile-page-teacher.jsp
Labels: bug

#47 Coupon function almost done
  src/main/java/net/enLearn/controller/AdminController.java
  src/main/java/net/enLearn/dao/RedeemCodeDAO.java
  src/main/java/net/enLearn/dao/RedeemCodeDAOImpl.java
  src/main/java/net/enLearn/service/RedeemCodeService.java
  src/main/java/net/enLearn/service/RedeemCodeServiceImpl.java
  src/main/webapp/WEB-INF/view/add-code.jsp
Labels: enhancement

#49 swee76-quiz-management-system
  .idea/artifacts/EnLearn_war.xml
  .idea/artifacts/EnLearn_war_exploded.xml
  src/main/webapp/WEB-INF/view/add-free-quiz.jsp
  src/main/webapp/WEB-INF/view/add-special-quiz.jsp
  src/main/webapp/WEB-INF/view/free-quiz-links.jsp
  src/main/webapp/WEB-INF/view/quiz-select-page.jsp
  src/main/webapp/resources/img/reshot-illustration-business-person-with-checklist-4FDRP8KNVW.png
  src/main/webapp/resources/img/reshot-illustration-woman-thinking-quizzes.png
Labels: good to merge

#68 swee76-quiz-management-system
  EnLearn.iml
  src/main/java/net/enLearn/controller/DemoController.java
  src/main/java/net/enLearn/controller/TeacherController.java
  src/main/java/net/enLearn/dao/FreeQuizDAO.java
  src/main/java/net/enLearn/dao/FreeQuizDAOImpl.java
  src/main/java/net/enLearn/service/FreeQuizService.java
  src/main/java/net/enLearn/service/FreeQuizServiceImpl.java
  src/main/webapp/WEB-INF/view/free-quiz-links.jsp
  src/main/webapp/WEB-INF/view/header.jsp
Labels: enhancement

#71 swee76-quiz-management-system
  src/main/java/net/enLearn/controller/DemoController.java
  src/main/java/net/enLearn/controller/TeacherController.java
  src/main/java/net/enLearn/dao/FreeQuizDAO.java
  src/main/webapp/WEB-INF/view/add-free-quiz.jsp
  src/main/webapp/WEB-INF/view/event-form.jsp
  src/main/webapp/WEB-INF/view/free-quiz-links.jsp
Labels: review needed, good to merge

#77 swee76-quiz-management-system
  .idea/artifacts/EnLearn_war.xml
  .idea/artifacts/EnLearn_war_exploded.xml
  EnLearn.iml
  src/main/webapp/WEB-INF/view/free-quiz-links.jsp
Labels: good to merge

#78 swee76-quiz-management-system
  src/main/java/net/enLearn/controller/CourseController.java
  src/main/java/net/enLearn/controller/DemoController.java
  src/main/java/net/enLearn/controller/TeacherController.java
  src/main/java/net/enLearn/dao/SpecialQuizDAO.java
  src/main/java/net/enLearn/dao/SpecialQuizDAOImpl.java
  src/main/java/net/enLearn/dao/StudentDAO.java
  src/main/java/net/enLearn/dao/StudentDAOImpl.java
  src/main/java/net/enLearn/dao/TeacherDAO.java
  src/main/java/net/enLearn/service/SpecialQuizService.java
  src/main/java/net/enLearn/service/SpecialQuizServiceImpl.java
  src/main/webapp/WEB-INF/view/add-special-quiz.jsp
  src/main/webapp/WEB-INF/view/free-quiz-links.jsp
  src/main/webapp/WEB-INF/view/header.jsp
Labels: enhancement, wontfix

#85 img-fix-dev-2.1
  src/main/webapp/WEB-INF/view/add-special-quiz.jsp
  src/main/webapp/WEB-INF/view/free-quiz-links.jsp
Labels: good to merge
